build: off

before_test:
# http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

- curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
- 7z x stack.zip stack.exe

clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"

test_script:
- stack setup --resolver=lts-9 > nul
- stack init  --resolver=lts-9 --solver
- echo "" | stack --no-terminal build --resolver=lts-9
- echo "" | stack --no-terminal test  --resolver=lts-9
- stack setup --resolver=nightly > nul
- echo "" | stack --no-terminal build --resolver=nightly
- echo "" | stack --no-terminal test  --resolver=nightly
